### ISSUE TITLE
Different colors for player and NPC in dialog box

### ISSUE THREAD

**Issue by naclander** [ManaPlus/ManaPlus#16]
When reading text (for quests, etc.) It is often hard to see where text was just written (either by the player responding, or by the NPC saying something new).

I believe showing NPC and player text in different colors would make reading dialog easier.

**Comment by 4144** [comment]
Server scripts can change npc text colors if need. This mean it depend on content.

I can add theme related npc and player text colors but player will cant change it from settings, because for now theme options cant be changed without xml editing.
