### ISSUE TITLE
KaOS Package

### ISSUE THREAD

**Issue by FiloSpaTeam** [ManaPlus/ManaPlus#18]
Hi!
tonight i created this package for KaOS operating system
[TMW](https://github.com/KaOS-Community-Packages/tmw)

See you in game!

**Comment by 4144** [comment]
Hi,
look like some error in dependencies. Dont need guichan and need many other sdl related pacakges, also libxml.
You can see in readme what other packages is need

**Comment by 4144** [comment]
also you using cmake, but it outdated and present here only for compilation for windows.

**Comment by FiloSpaTeam** [comment]
good! Thanks! i started from an old package of TMW and tried to updated later. Maybe i don't have seen right dependecies ;-) Update now! :+1:

**Comment by 4144** [comment]
oh also name. the mana world is old client name, now it ManaPlus

**Comment by FiloSpaTeam** [comment]
yeah. right! Other deps. need to be solved/ are not useful? Thanks!

**Comment by 4144** [comment]
look like PKGBUILD similar to arch linux format, you can see deps in PKGBUILD inside manaplus sources. But this file by itself not working in latest arch linux.

**Comment by FiloSpaTeam** [comment]
Becaus KaOS use the ABS (Arch build system) but is indipendent now. Packages are differents, KaOS is only x86_64...

**Comment by FiloSpaTeam** [comment]
For archlinux my PKGBUILD is good. need only to substitute the wrong name of packages with right name.

**Comment by FiloSpaTeam** [comment]
Later i ll remove unused deps. Thanks ;-)

**Comment by 4144** [comment]
Link added
