### ISSUE TITLE
ManaPlus Client/Server for the Raspberry PI 3 ?  

### ISSUE THREAD

**Issue by spartrekus** [ManaPlus/ManaPlus#25]
Hello,

I would be pleased to find a package of the Manaplus Server for the Raspberry (running Debian Stable). 

The Manaplus Client (stable Debian) is too old to find an appropriate server, in English language.

Would you maybe have a easy to compile Manaplus Server for Raspberry so that one can setup a home server for playing with several users?

Brazilian/Portugese server would word on such Raspberry Manaplus 1.4.10.11-1 but it is not in English language unfortunately.  

thank you

**Comment by 4144** [comment]
Try use manaplus from backports. In stable backports should be 1.7.1.x

In custom repos sadly only i386 and amd64 builds

**Comment by spartrekus** [comment]
backports on Rasspberry ? Sounds difficult. 

Do not you think that to allow : 

1) Maybe, make the ManaPlus Server easier to compile on the Raspberry PI 3 ?
    Or actually, it would be good that a debian package for the server would be available on a default 
    debian (deb) file so that users can expand the list of servers. There are unfortunately too few. 

2) Client: on my RPI, 
    Maybe someone has an old PC or another Raspberry and internet to    
    create a default ManaPlus Server that allows 1.4.x versions

Poor man people cannot play MMORPG / Manaplus despite they would be be greatly happy to play also Manaplus World. (in english)

I think about Afrika and some poor country where the Raspberry is highly important for education.

Gaming is also important  for everyone - part of life and fun.

**Comment by 4144** [comment]
Here no manaplus server.
Exists only server software with name tmwa (now this is legacy server). Most games still using it.
And hercules server software. Now it used only by "evol online" and "the mana world test server"

For any platform possible to build manaplus. Even for pasberrypi.

**Comment by 4144** [comment]
Backports i mean add line with backports into sources.list. And you will can install some updated software.
Something like this:
```
deb http://deb.debian.org/debian jessie-backports main
```
If your distro based on debian older than jessie, then only build from sources.

**Comment by spartrekus** [comment]
- This is why Eternal Lands is better. It works always, over the time. You can keep your user account.
But you need a configuration of a rich man.

A poor man need 2D aka Mana, but also stable as does EternalLands.
- Mana*: 
There is not even a stable, welcoming, server over time. 
Server is 

Evol will replace ManaWorld and then again same story no server. 

Could the author of ManaPlus dedicate forever one machine: 
.1 for manaplus 1.4.x versions 
.2 for 1.4 -1.7 versions manaplus
.3 evol (do what you want - it is not that good compared to mana) 

The DEV tries to force users to use Evol - somehow - since Mana World can disappeear.

The  major problem is that you cannot compile - well - painless the ManaPlus-Server. 
If stand alone people with helping willing intentions cannot help easily the development of ManaPlus, then, do not wonder that ManaPlus is NOT SO MUCH known and used. 

Look, for instance, rAthena, it is clean to compile the server. 
./configure ; make ; sudo make install works well. 
I could easily compile it myself on the raspberry PI. 
https://github.com/rathena/rathena

ManaWorld Server is not the same story at all.  

There is no backport on raspberry since it is an ARMHF and it needs a clean GCC compiler. 


**If someone want to help, please set up a welcoming server in ENGLISH exactly or similar to ManaWorld Plus Server (Brazil). Their server is clean, welcoming persons, and accept older versions of ManaPlus Clients (i..e the version of the Raspberry PI).**

**Comment by 4144** [comment]
Again manaplus server not exists.
Please say what server you mean. About both both existing server software i already wrote before.
Probably you mean legacy server aka tmwa? It not maintained anymore. Not sure is it can be compiled on arm. But full instruction exists too.

Actual server (hercules) you can build for arm too. And full instruction exists too.

About rarhena you forgot all other stteps. Any software can be compiled with ./configure, make. But after need long configuration, like add configs, add passwords etc.

If you have any issue with new server (hercules based), report on any project in here https://gitlab.com/evol/.
For tmwa (legacy server) you cant report any issues.

Closing because it not related to manaplus.
