### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by AsciiWolf** [ManaPlus/ManaPlus#33]
I have made a Flatpak build of ManaPlus and sent it as a PR for review to Flathub.

@4144 If you or another ManaPlus staff member want access to the repo once it is on Flathub, feel free to let us know [here](https://github.com/flathub/flathub/pull/1139). Thanks!

**Comment by 4144** [comment]
look like build failed

**Comment by AsciiWolf** [comment]
Yep, the AppData file seems to have issues. I will write a patch to fix this.

**Comment by AsciiWolf** [comment]
I have fixed it and have also sent the fixes as PRs #34 and #35.

**Comment by AsciiWolf** [comment]
ManaPlus is now on [Flathub](https://flathub.org).
