### ISSUE TITLE
MinGW: Can't Build

### ISSUE THREAD

**Issue by AntumDeluge** [ManaPlus/ManaPlus#39]
I've been trying to build the client with MinGW, but getting an error about a missing file:

```
config.status: error: cannot find input file: `data/tmw/tmw.desktop.in'
```

**Edit:** I reverted d040990961feaa5f6570df096cf43afa892a23c7, re-ran `autoreconf -i`, but now have a new error:

```
make[2]: Entering directory '/home/Jordan/Development/TMW/builds/ManaPlus-upstream-Win64-SDL12/data/tmw'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/home/Jordan/Development/TMW/builds/ManaPlus-upstream-Win64-SDL12/data/tmw'
make[1]: *** [Makefile:349: all-recursive] Error 1
make[1]: Leaving directory '/home/Jordan/Development/TMW/builds/ManaPlus-upstream-Win64-SDL12/data'
make: *** [Makefile:480: all-recursive] Error 1
```

[config.log](https://github.com/ManaPlus/ManaPlus/files/9113683/config.log)

**Comment by AntumDeluge** [comment]
I re-enabled CMake builds & can now build with that.

**Comment by 4144** [comment]
about your deleted message. cmake is legacy, it may not works or works wrong.

**Comment by AntumDeluge** [comment]
> idk why you revert this commit, it should works as is.

I reverted it because that is the commit that deleted the file in the error output so I could see if it would work.

> cmake is legacy, it may not works or works wrong.

I only started experimenting with CMake after I couldn't get the builds to work with the included GNU Autotools.

> i not see any issues in mingw or in native builds.

So, this is why I am asking. Since you are able to build with MinGW/GNU Autotools, what might my issue be?

**Comment by AntumDeluge** [comment]
Can you help me understand why I am getting the error:

```
config.status: error: cannot find input file: `data/tmw/tmw.desktop.in'
```

**Comment by 4144** [comment]
this error look like because you using wrong configure file. This is temporary file and left probably from your old builds.

for update it, need run ``autoreconf`` or ``autoreconf -i``

You also can try clone manaplus into new directory and will be need run ``autoreconf`` too.

**Comment by AntumDeluge** [comment]
Thanks, that was the problem. Residual configuration files. Config succeeded. Now compiling.
